server:
  port: 8166
  servlet:
    context-path: /web-market-carts
utils:
  cart:
    prefix: SPRING_WEB_APP_
    statistic: statistic
integrations:
  core-service:
    coreServiceUrl: http://localhost:5555/core
    readTimeout: 10000
    writeTimeout: 2000
    connectionTimeout: 2000

